language: python

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq -y update

env:
  - QGIS_REPO=http://qgis.org/debian-ltr
#  - QGIS_REPO=http://qgis.org/debian-nightly-release

install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - sudo pip install nose2 cov-core python-coveralls pep8

before_script:
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - export PATH=/usr/bin:$PATH
  - pep8 resource_sharing
  - xvfb-run nose2 -s test --with-coverage

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f55e2fa1a258c0906e3b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

