name: "ðŸ“š Documentation"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/*/**"
      - "requirements/documentation.txt"
    tags: "*"

env:
  PYTHON_VERSION: 3.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3.0.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/documentation.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -U -r requirements/documentation.txt
          python -m pip install -U ghp-import

      - name: Build doc using Sphinx
        run: sphinx-build -b html docs docs/_build/html

      - name: Upload doc as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Documentation HTML build
          path: docs/_build

      - name: Deploy to GitHub Pages
        run: ghp-import --force --no-history --no-jekyll --push docs/_build/html
